name: bt_nhom3
description: "A Flutter project for group 3."
publish_to: 'none'

# Version information
version: 1.0.0+1

# Dart and Flutter SDK environment
environment:
  sdk: ">=3.5.0 <4.0.0"

# Project dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific configuration
flutter:
  uses-material-design: true

  # Asset configuration
  assets:
    - asset/    # Changed from asset\ to assets/